package controller;

import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import java.io.IOException;
import java.util.ArrayList;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.Spinner;
import javafx.scene.control.SpinnerValueFactory;
import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;

public class GenerazioneCommesseController {

	@FXML
	private AnchorPane contentPaneGenerazioneCommesse;
	
	@FXML
	private Label nomeCommessaTF;
	String nome;
	
	@FXML
	private Spinner<Integer> durataMassimaTF;
	 int durataMassima;
	
	@FXML
	private Label idGeneratoLabel;
	int i = 3; 
	
	@FXML
	private TextArea descrizioneTA;
	String descrizione;
	
	@FXML
	private Button aggiungiButton;
	
	 private ArrayList<String> valori = new ArrayList<>();
	 
	 
	
	 //MANCA LA LOGICA PER GENERARE ID
	 
	    @FXML
	    public void initialize() {
	    	durataMassimaTF.setValueFactory(new SpinnerValueFactory.IntegerSpinnerValueFactory(1, 100, 0));   
	    	
	    	
	        // Aggiungi azione al pulsante
	        aggiungiButton.setOnAction(event -> {
	            nome = nomeCommessaTF.getText();
	            descrizione = descrizioneTA.getText();
	            durataMassima = durataMassimaTF.getValue();	            	            
		        idGeneratoLabel.setText(String.valueOf(i));  	
	            
	            if (nome.isEmpty() || descrizione.isEmpty() || durataMassima == 0) {
	                System.out.println("Errore: tutti i campi devono essere compilati.");
	                return;
	            }

	            System.out.println(this.getNome() + this.getDescrizione() + this.getDurataMassima() + this.getid());	            
	        });
	    }
	    
	    
	    public String getNome() {
	    	return this.nome;
	    }
	    
	    public String getDescrizione() {
	    	return this.descrizione;
	    }
	    
	    public int getDurataMassima() {
	    	return this.durataMassima;
	    }
	    
	    public int getid() {
	    	return this.i;
	    }
	    
	    
	
	@FXML
	public void switchToGenerazioneCommesse(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		 System.out.println("sono entrato in modalità visualizza commesse");

	        // Carica il file FXML di inserimentoTask.fxml
	        Parent root = FXMLLoader.load(getClass().getResource("/VisualizzaCommesse.fxml"));

	        contentPaneGenerazioneCommesse.getChildren().clear();  // Rimuovi il contenuto precedente
	        contentPaneGenerazioneCommesse.getChildren().add(root);  // Aggiungi il nuovo contenuto
	         
	}

    
    
    
	
	
}
