package controller;

import javafx.scene.control.Label;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;

import java.io.IOException;
import java.util.ArrayList;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Spinner;
import javafx.scene.control.SpinnerValueFactory;
import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import model.Reparto;

public class GenerazioneCommesseController {

	@FXML
	private AnchorPane contentPaneGenerazioneCommesse;

	@FXML
	private TextField nomeCommessaTF;
	String nome;

	@FXML
	private TextArea descrizioneTA;
	String descrizione;
	
	@FXML
	private ComboBox<Reparto> comboReparto;
	@FXML
	private Button aggiungiButton;

	private ArrayList<String> valori = new ArrayList<>();

	// MANCA LA LOGICA PER GENERARE ID

	@FXML
	public void initialize() {

		aggiungiButton.setOnAction(event -> {
			nome = nomeCommessaTF.getText();
			descrizione = descrizioneTA.getText();

			if (nome.isEmpty() || descrizione.isEmpty()) {
				System.out.println("Errore: tutti i campi devono essere compilati.");
				return;
			}

			System.out.println(this.getNome() + this.getDescrizione() );
		});
	}

	public String getNome() {
		return this.nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}


	@FXML
	public void switchToGenerazioneCommesse(ActionEvent event) throws IOException {
		// TODO Autogenerated

		System.out.println("sono entrato in modalità visualizza commesse");

		// Carica il file FXML di inserimentoTask.fxml
		Parent root = FXMLLoader.load(getClass().getResource("/manager/VisualizzaCommesse.fxml"));

		contentPaneGenerazioneCommesse.getChildren().clear(); // Rimuovi il contenuto precedente
		contentPaneGenerazioneCommesse.getChildren().add(root); // Aggiungi il nuovo contenuto

	}

}
