package controller;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.GridPane;


//MANCA IL METODO VISUALIZZA COMMESSA

public class VisualizzaCommesseController {

	@FXML
	private AnchorPane contentPaneVisualizzaCommesse;
	
	@FXML
	public void SwitchToGenerazioneCommesse(ActionEvent event) throws IOException {
		// TODO Autogenerated
		
		 System.out.println("sono entrato in modalità generazione commesse");

	        // Carica il file FXML di inserimentoTask.fxml
	        Parent root = FXMLLoader.load(getClass().getResource("/GenerazioneCommesse.fxml"));

	        contentPaneVisualizzaCommesse.getChildren().clear();  // Rimuovi il contenuto precedente
	        contentPaneVisualizzaCommesse.getChildren().add(root);  // Aggiungi il nuovo contenuto
	}
	
	
	

	}
	

